/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PreviewDothtmlRouteImport } from './routes/preview[.]html'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AppointmentsIdRouteImport } from './routes/appointments.$id'
import { Route as BookIndexRouteImport } from './routes/book/index'
import { Route as BookConfirmationRouteImport } from './routes/book/confirmation'
import { Route as BookDatetimeRouteImport } from './routes/book/datetime'
import { Route as BookDetailsRouteImport } from './routes/book/details'
import { Route as BookReviewRouteImport } from './routes/book/review'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as NotificationsIdRouteImport } from './routes/notifications.$id'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileSupportRouteImport } from './routes/profile.support'
import { Route as HomeServiceIdRouteImport } from './routes/home.service.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDothtmlRoute = PreviewDothtmlRouteImport.update({
  id: '/preview.html',
  path: '/preview.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIdRoute = AppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppointmentsRoute,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmationRoute = BookConfirmationRouteImport.update({
  id: '/book/confirmation',
  path: '/book/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDatetimeRoute = BookDatetimeRouteImport.update({
  id: '/book/datetime',
  path: '/book/datetime',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDetailsRoute = BookDetailsRouteImport.update({
  id: '/book/details',
  path: '/book/details',
  getParentRoute: () => rootRouteImport,
} as any)
const BookReviewRoute = BookReviewRouteImport.update({
  id: '/book/review',
  path: '/book/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)
const NotificationsIdRoute = NotificationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotificationsRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSupportRoute = ProfileSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ProfileRoute,
} as any)
const HomeServiceIdRoute = HomeServiceIdRouteImport.update({
  id: '/service/$id',
  path: '/service/$id',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/preview.html': typeof PreviewDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/book/confirmation': typeof BookConfirmationRoute
  '/book/datetime': typeof BookDatetimeRoute
  '/book/details': typeof BookDetailsRoute
  '/book/review': typeof BookReviewRoute
  '/chat/$id': typeof ChatIdRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/support': typeof ProfileSupportRoute
  '/book/': typeof BookIndexRoute
  '/home/service/$id': typeof HomeServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/preview.html': typeof PreviewDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/book/confirmation': typeof BookConfirmationRoute
  '/book/datetime': typeof BookDatetimeRoute
  '/book/details': typeof BookDetailsRoute
  '/book/review': typeof BookReviewRoute
  '/chat/$id': typeof ChatIdRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/support': typeof ProfileSupportRoute
  '/book': typeof BookIndexRoute
  '/home/service/$id': typeof HomeServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/preview.html': typeof PreviewDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/book/confirmation': typeof BookConfirmationRoute
  '/book/datetime': typeof BookDatetimeRoute
  '/book/details': typeof BookDetailsRoute
  '/book/review': typeof BookReviewRoute
  '/chat/$id': typeof ChatIdRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/support': typeof ProfileSupportRoute
  '/book/': typeof BookIndexRoute
  '/home/service/$id': typeof HomeServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/chat'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/preview.html'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/terms'
    | '/verify'
    | '/appointments/$id'
    | '/book/confirmation'
    | '/book/datetime'
    | '/book/details'
    | '/book/review'
    | '/chat/$id'
    | '/notifications/$id'
    | '/profile/edit'
    | '/profile/support'
    | '/book/'
    | '/home/service/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/chat'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/preview.html'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/terms'
    | '/verify'
    | '/appointments/$id'
    | '/book/confirmation'
    | '/book/datetime'
    | '/book/details'
    | '/book/review'
    | '/chat/$id'
    | '/notifications/$id'
    | '/profile/edit'
    | '/profile/support'
    | '/book'
    | '/home/service/$id'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/chat'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/preview.html'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/terms'
    | '/verify'
    | '/appointments/$id'
    | '/book/confirmation'
    | '/book/datetime'
    | '/book/details'
    | '/book/review'
    | '/chat/$id'
    | '/notifications/$id'
    | '/profile/edit'
    | '/profile/support'
    | '/book/'
    | '/home/service/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PreviewDothtmlRoute: typeof PreviewDothtmlRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  BookConfirmationRoute: typeof BookConfirmationRoute
  BookDatetimeRoute: typeof BookDatetimeRoute
  BookDetailsRoute: typeof BookDetailsRoute
  BookReviewRoute: typeof BookReviewRoute
  BookIndexRoute: typeof BookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview.html': {
      id: '/preview.html'
      path: '/preview.html'
      fullPath: '/preview.html'
      preLoaderRoute: typeof PreviewDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$id': {
      id: '/appointments/$id'
      path: '/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppointmentsIdRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmation': {
      id: '/book/confirmation'
      path: '/book/confirmation'
      fullPath: '/book/confirmation'
      preLoaderRoute: typeof BookConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/datetime': {
      id: '/book/datetime'
      path: '/book/datetime'
      fullPath: '/book/datetime'
      preLoaderRoute: typeof BookDatetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/details': {
      id: '/book/details'
      path: '/book/details'
      fullPath: '/book/details'
      preLoaderRoute: typeof BookDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/review': {
      id: '/book/review'
      path: '/book/review'
      fullPath: '/book/review'
      preLoaderRoute: typeof BookReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/notifications/$id': {
      id: '/notifications/$id'
      path: '/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof NotificationsIdRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/support': {
      id: '/profile/support'
      path: '/support'
      fullPath: '/profile/support'
      preLoaderRoute: typeof ProfileSupportRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/home/service/$id': {
      id: '/home/service/$id'
      path: '/service/$id'
      fullPath: '/home/service/$id'
      preLoaderRoute: typeof HomeServiceIdRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface AppointmentsRouteChildren {
  AppointmentsIdRoute: typeof AppointmentsIdRoute
}

const AppointmentsRouteChildren: AppointmentsRouteChildren = {
  AppointmentsIdRoute: AppointmentsIdRoute,
}

const AppointmentsRouteWithChildren = AppointmentsRoute._addFileChildren(
  AppointmentsRouteChildren,
)

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface HomeRouteChildren {
  HomeServiceIdRoute: typeof HomeServiceIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeServiceIdRoute: HomeServiceIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface NotificationsRouteChildren {
  NotificationsIdRoute: typeof NotificationsIdRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsIdRoute: NotificationsIdRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileSupportRoute: typeof ProfileSupportRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileSupportRoute: ProfileSupportRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PreviewDothtmlRoute: PreviewDothtmlRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  BookConfirmationRoute: BookConfirmationRoute,
  BookDatetimeRoute: BookDatetimeRoute,
  BookDetailsRoute: BookDetailsRoute,
  BookReviewRoute: BookReviewRoute,
  BookIndexRoute: BookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
